<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\PhanChiThong_DataAccess\PhanChiThong_DataAccess.csproj" />
    <ProjectReference Include="..\PhanChiThong_BusinessLogic\PhanChiThong_BusinessLogic.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
